name: Check and update latest eLab version every day

on:
    # run every day at 1:01
    schedule:
    - cron: "05 12 * * *"

jobs:
    # adapted from https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release
    increment-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout this repo
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.REPO_TOKEN }}
              
            - name: Get release version
              run: |
                curl -sL https://api.github.com/repos/elabftw/elabftw/releases/latest | \
                jq -r ".tag_name" > latest_build
                
            - name: check for modified files
              id: git-check
              run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
              
            - name: Commit latest release version
              if: steps.git-check.outputs.modified == 'true'
              run: |
                git config --global user.name 'din14970'
                git config --global user.email 'din14970@users.noreply.github.com'
                git commit -am "New release eLabFTW"
                git push
                
