name: Deploy arm32 image of hypernext to Docker

on:
    # run every day at 1:00
    schedule:
    - cron: "00 01 * * *"
    push:
        paths:
          - '.github/workflows/make_hypernext_arm32.yml'

jobs:
    buildandpush:
        runs-on: ubuntu-latest
        env:
            BRANCHNAME: hypernext
            DOCKER_FILE: Dockerfile
        steps:    
            - name: Checkout elabimg repo on latest tag
              uses: actions/checkout@v2
              with:
                  repository: "elabftw/elabimg"
                  ref: ${{ env.BRANCHNAME }}
                  
            - name: Modify the JDK version until openjdk11 is available on armv7
              run: |
                sed -i "s/openjdk11-jre/openjdk8-jre/g" Dockerfile
                
            # cypress does not have ARM7 builds, also dependency issue with ARM64 builds
            - name: Add a command in the Dockerfile to remove cypress as a dependency in package.json
              run: |
                sed -i '/WORKDIR \/elabftw/a\\nRUN if \[ "\$TARGETPLATFORM" = "linux/arm/v7" \]; then sed -i "/cypress/d" package.json; fi' Dockerfile
    
            - name: View dockerfile
              run: |
                cat Dockerfile
                  
            # https://github.com/docker/setup-qemu-action#usage
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            # https://github.com/marketplace/actions/docker-setup-buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            # https://github.com/docker/login-action#docker-hub
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}

            # https://github.com/docker/build-push-action#multi-platform-image
            - name: Build latest release for all platforms and push to Docker Hub
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ${{ env.DOCKER_FILE }}
                platforms: linux/arm/v7
                push: true
                build-args: |
                    ELABFTW_VERSION=hypernext
                    ELABIMG_VERSION=hypernext
                tags: |
                    ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.BRANCHNAME }}-arm32
